hostname: dal.edge01
routerid: 192.0.2.255
interfaces:
  lo0 unit 0:
    verb: set
    family: inet
    address: 192.0.2.255/32
  ge-0/0/1 unit 0:
    verb: set
    family: inet
    address: 192.0.2.1/26
bgp:
  asn: 64000
  peers:
    ThisPeerName:
      verb: set
      asn: 64000
      description: "Internal session with ThisPeerName"
      local_address: 192.0.2.1
      neighbor: 192.0.2.2
    ThatPeerName:
      verb: set
      asn: 64002
      description: "External session with ThatPeerName"
      local_address: 192.0.2.1
      neighbor: 192.0.2.3
